import type {
  CompleteCanvasRequest,
  EnsureDraftRequest,
  MergeRequest,
  PushEventPayload,
  PushEventsRequest,
  RenameHandleRequest,
  TransferConsumeRequest,
} from "../shared/paint-types.d.ts";
import { normalizeTransferCode } from "../shared/transfer-code.js";

export const MAX_EVENTS_PER_PUSH = 64;
export const MAX_JSON_BODY_BYTES = 160_000;
const MAX_CELL_BYTES = 256 * 6;
// The prototype generated 20-character sortable ids. Keep accepting those so
// an existing local draft or signed painting remains usable, while every new
// id is the standard 26-character shape generated by shared/ulid.js.
const ULID = /^(?:[0-9A-HJKMNP-TV-Z]{20}|[0-9A-HJKMNP-TV-Z]{26})$/;

export class HttpError extends Error {
  constructor(public status: number, message: string) {
    super(message);
  }
}

export function assertCanvasId(value: string): void {
  if (!ULID.test(value)) throw new HttpError(400, "invalid canvas id");
}

export function assertSameOrigin(req: Request): void {
  const origin = req.headers.get("origin");
  if (origin && origin !== new URL(req.url).origin) {
    throw new HttpError(403, "cross-origin mutation rejected");
  }
}

export async function readJsonBody(
  req: Request,
  maxBytes = MAX_JSON_BODY_BYTES,
): Promise<unknown> {
  const contentType = req.headers.get("content-type")?.split(";", 1)[0].trim();
  if (contentType !== "application/json") {
    throw new HttpError(415, "content-type must be application/json");
  }
  const declaredLength = Number(req.headers.get("content-length") ?? "0");
  if (Number.isFinite(declaredLength) && declaredLength > maxBytes) {
    throw new HttpError(413, "request body is too large");
  }

  const reader = req.body?.getReader();
  if (!reader) throw new HttpError(400, "request body is required");
  const chunks: Uint8Array[] = [];
  let length = 0;
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    length += value.byteLength;
    if (length > maxBytes) {
      await reader.cancel();
      throw new HttpError(413, "request body is too large");
    }
    chunks.push(value);
  }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.byteLength;
  }
  try {
    return JSON.parse(new TextDecoder().decode(bytes));
  } catch {
    throw new HttpError(400, "request body must contain valid JSON");
  }
}

function record(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new HttpError(400, "request body must be an object");
  }
  return value as Record<string, unknown>;
}

function nullableString(value: unknown): string | null {
  if (value === null || value === undefined) return null;
  if (typeof value !== "string") {
    throw new HttpError(400, "invalid event field");
  }
  return value;
}

function validateCells(value: unknown): string | null {
  if (value === null || value === undefined) return null;
  if (typeof value !== "string") {
    throw new HttpError(400, "cells must be base64");
  }
  let bytes: Uint8Array;
  try {
    bytes = Uint8Array.from(
      atob(value),
      (character) => character.charCodeAt(0),
    );
  } catch {
    throw new HttpError(400, "cells must be valid base64");
  }
  if (
    bytes.byteLength === 0 || bytes.byteLength > MAX_CELL_BYTES ||
    bytes.byteLength % 6 !== 0
  ) {
    throw new HttpError(400, "cells has an invalid length");
  }
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const indexes = new Set<number>();
  for (let offset = 0; offset < bytes.byteLength; offset += 6) {
    const index = view.getUint16(offset);
    if (index >= 256 || indexes.has(index)) {
      throw new HttpError(400, "cells contains an invalid pixel index");
    }
    indexes.add(index);
  }
  return value;
}

function validateEvent(value: unknown, now: number): PushEventPayload {
  const event = record(value);
  if (typeof event.id !== "string" || !ULID.test(event.id)) {
    throw new HttpError(400, "invalid event id");
  }
  if (event.kind !== "stroke" && event.kind !== "undo") {
    throw new HttpError(400, "invalid event kind");
  }
  if (
    !Number.isSafeInteger(event.clientTs) || Number(event.clientTs) < 0 ||
    Number(event.clientTs) > now + 300_000
  ) {
    throw new HttpError(400, "invalid client timestamp");
  }
  const strokeId = nullableString(event.strokeId);
  const revertsId = nullableString(event.revertsId);
  const cells = validateCells(event.cells);
  if (
    event.kind === "stroke" &&
    (!strokeId || !ULID.test(strokeId) || !cells || revertsId)
  ) {
    throw new HttpError(400, "invalid stroke event");
  }
  if (
    event.kind === "undo" &&
    (strokeId || cells || !revertsId || !ULID.test(revertsId))
  ) {
    throw new HttpError(400, "invalid undo event");
  }
  return {
    id: event.id,
    kind: event.kind,
    strokeId,
    cells,
    revertsId,
    clientTs: Number(event.clientTs),
  };
}

export function validatePushEvents(
  value: unknown,
  now = Date.now(),
): PushEventsRequest {
  const body = record(value);
  if (!Array.isArray(body.events) || body.events.length > MAX_EVENTS_PER_PUSH) {
    throw new HttpError(400, "events must be a bounded array");
  }
  if (typeof body.heartbeatActive !== "boolean") {
    throw new HttpError(400, "heartbeatActive must be boolean");
  }
  const events = body.events.map((event) => validateEvent(event, now));
  if (new Set(events.map((event) => event.id)).size !== events.length) {
    throw new HttpError(400, "event ids must be unique within a push");
  }
  return {
    events,
    heartbeatActive: body.heartbeatActive,
  };
}

export function validateCompletion(value: unknown): CompleteCanvasRequest {
  const body = record(value);
  if (typeof body.title !== "string") {
    throw new HttpError(400, "title must be text");
  }
  const title = body.title.trim();
  if (title.length === 0 || [...title].length > 16) {
    throw new HttpError(400, "title must contain 1 to 16 characters");
  }
  return { title };
}

export function validateEnsureDraft(value: unknown): EnsureDraftRequest {
  const body = record(value);
  if (typeof body.id !== "string") {
    throw new HttpError(400, "draft id is required");
  }
  assertCanvasId(body.id);
  return { id: body.id };
}

// Letters, digits, spaces, and a small, deliberately restrictive
// punctuation set (apostrophe, period, hyphen) — enough for names like
// "O'Brien" or "J. R." without opening the door to control characters,
// newlines, or anything that would make a handle awkward to display
// plainly wherever it's shown (password manager sheets, /collection, a
// future author byline). No profanity filtering — out of scope for a
// hobby project, and a losing game to try to win.
const HANDLE_PATTERN = /^[A-Za-z0-9' .-]+$/;

export function validateHandleRename(value: unknown): RenameHandleRequest {
  const body = record(value);
  if (typeof body.handle !== "string") {
    throw new HttpError(400, "handle must be text");
  }
  // Validate the RAW input against the charset allowlist FIRST — before
  // any normalization. `\s` (used by a naive "collapse whitespace" regex)
  // matches \n, \t, \r, and friends, not just the space character, so
  // collapsing whitespace before this check would launder a newline into
  // a legal space and silently rewrite what the user actually typed.
  // Rejecting control characters outright, THEN normalizing only literal
  // spaces, means the handle stored is either exactly what was typed
  // (mod leading/trailing/repeated spaces) or rejected — never silently
  // transformed into different text. This matters beyond validation
  // hygiene: a handle is public author text on signed paintings.
  if (!HANDLE_PATTERN.test(body.handle)) {
    throw new HttpError(
      400,
      "handle may only contain letters, digits, spaces, apostrophes, periods, and hyphens",
    );
  }
  // Only literal spaces (not \s) are collapsed/trimmed — a value that
  // reaches this point has already been proven free of \n/\t/\r/etc.
  const handle = body.handle.trim().replace(/ {2,}/g, " ");
  const length = [...handle].length;
  if (length < 3 || length > 32) {
    throw new HttpError(400, "handle must contain 3 to 32 characters");
  }
  return { handle };
}

export function validateMergeRequest(value: unknown): MergeRequest {
  const body = record(value);
  if (typeof body.mergeToken !== "string" || body.mergeToken.length === 0) {
    throw new HttpError(400, "mergeToken is required");
  }
  if (body.keep !== "device" && body.keep !== "account") {
    throw new HttpError(400, 'keep must be "device" or "account"');
  }
  return { mergeToken: body.mergeToken, keep: body.keep };
}

export function validateTransferConsume(value: unknown): TransferConsumeRequest {
  const body = record(value);
  if (typeof body.code !== "string") {
    throw new HttpError(400, "code is required");
  }
  const code = normalizeTransferCode(body.code);
  if (!code) {
    throw new HttpError(400, "that doesn't look like a transfer code");
  }
  return { code };
}
